// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Accumulation = "zero" | "lessThan20" | "from20To40" | "moreThan40" | "unknown";
