// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Enum for the multi-select question. This is for use in Rust logic.
 * The database will still store a JSON string of selected options.
 */
export type AreaToAvoid = "terrainTraps" | "startZones" | "avyPaths" | "runoutZones" | "slope30To35" | "slopeGreaterThan35" | "convexUnsupported" | "leeLoaded" | "sunny" | "slopeSizeLarge" | "slopeSizeMedium" | "slopeSizeSmall" | "overheadHazard";
