// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AreaToAvoid = "terrainTraps" | "startZones" | "avyPaths" | "runoutZones" | "slope30To35" | "slopeGreaterThan35" | "convexUnsupported" | "leeLoaded" | "sunny" | "slopeSizeLarge" | "slopeSizeMedium" | "slopeSizeSmall" | "overheadHazard";
