// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Confidence } from "./Confidence";
import type { DangerRating } from "./DangerRating";
import type { MacroTrend } from "./MacroTrend";

export type AvalancheForecast = { id: number, tripId: number, forecastAlp: DangerRating | null, forecastTl: DangerRating | null, forecastBtl: DangerRating | null, macroTrends: MacroTrend | null, confidence: Confidence | null, comment: string | null, };
