// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Elevation } from "./Elevation";
import type { ProblemType } from "./ProblemType";

export type AvalancheProblem = { id: number, forecastId: number, elevation: Elevation, problemType: ProblemType, };
