// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AvalancheSize = "none" | "lessThan1" | "from15To2" | "moreThan25" | "unknown";
