// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AvalancheSize } from "./AvalancheSize";
import type { AvalancheTrigger } from "./AvalancheTrigger";
import type { InstabilityObservation } from "./InstabilityObservation";
import type { ProblemType } from "./ProblemType";
import type { TestResult } from "./TestResult";

export type AvyObservation = { id: number, tripId: number, observationTime: string, avyActivitySize: AvalancheSize | null, avyActivityTrigger: AvalancheTrigger | null, avyActivityCharacteristic: ProblemType | null, instabilitySeeFeel: InstabilityObservation | null, instabilityCt: TestResult | null, instabilityEct: TestResult | null, comment: string | null, };
