// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Accumulation } from "./Accumulation";
import type { AvalancheSize } from "./AvalancheSize";
import type { AvalancheTrigger } from "./AvalancheTrigger";
import type { InstabilityObservation } from "./InstabilityObservation";
import type { Precipitation } from "./Precipitation";
import type { ProblemType } from "./ProblemType";
import type { SolarRadiation } from "./SolarRadiation";
import type { TestResult } from "./TestResult";
import type { WindDirection } from "./WindDirection";
import type { WindSpeed } from "./WindSpeed";

export type FieldObservation = { id: number, tripId: number, observationTime: string, precipitation: Precipitation | null, accumulation: Accumulation | null, windSpeed: WindSpeed | null, windDirection: WindDirection | null, solarRadiation: SolarRadiation | null, avyActivitySize: AvalancheSize | null, avyActivityTrigger: AvalancheTrigger | null, avyActivityCharacteristic: ProblemType | null, instabilitySeeFeel: InstabilityObservation | null, instabilityCt: TestResult | null, instabilityEct: TestResult | null, comments: string | null, };
