// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AvalancheForecast } from "./AvalancheForecast";
import type { AvalancheProblem } from "./AvalancheProblem";
import type { AvyObservation } from "./AvyObservation";
import type { TripPlanning } from "./TripPlanning";
import type { Weather } from "./Weather";

export type FullTripDetails = { forecast: AvalancheForecast | null, planning: TripPlanning | null, problems: Array<AvalancheProblem>, weatherObservations: Array<Weather>, avyObservations: Array<AvyObservation>, id: number, name: string, tripDate: string, };
