// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AvalancheForecast } from "./AvalancheForecast";
import type { AvalancheProblem } from "./AvalancheProblem";
import type { AvyObservation } from "./AvyObservation";
import type { TripPlan } from "./TripPlan";
import type { Weather } from "./Weather";

export type FullTripDetails = { forecast: AvalancheForecast | null, forecastProblems: Array<AvalancheProblem>, plan: TripPlan | null, weatherObservations: Array<Weather>, avyObservations: Array<AvyObservation>, id: number, name: string, tripDate: string, };
