// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AvalancheForecast } from "./AvalancheForecast";
import type { AvalancheProblem } from "./AvalancheProblem";
import type { FieldObservation } from "./FieldObservation";
import type { TripPlanning } from "./TripPlanning";

export type FullTripDetails = { forecast: AvalancheForecast | null, planning: TripPlanning | null, problems: Array<AvalancheProblem>, observations: Array<FieldObservation>, id: number, name: string, tripDate: string, };
