// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Accumulation } from "./Accumulation";
import type { Precipitation } from "./Precipitation";
import type { SolarRadiation } from "./SolarRadiation";
import type { WindDirection } from "./WindDirection";
import type { WindSpeed } from "./WindSpeed";

export type NewWeather = { tripId: number, observationTime: string | null, precipitation: Precipitation | null, accumulation: Accumulation | null, windSpeed: WindSpeed | null, windDirection: WindDirection | null, solarRadiation: SolarRadiation | null, comment: string | null, };
