// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ProblemType = "looseDry" | "looseWet" | "wetSlab" | "cornices" | "windSlabs" | "stormSlabs" | "persistentSlabs" | "deepPersistentSlabs";
