// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AreasToAvoid } from "./AreasToAvoid";

export type TripPlanning = { id: number, tripId: number, areasToAvoid: AreasToAvoid | null, planLeftWithSomeone: boolean, decisionPointsConsidered: boolean, decisionPointsComment: string | null, };
